services:
  - type: web
    name: backend-ag-api
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python manage.py makemigrations --noinput && python manage.py migrate --noinput && gunicorn tutorial.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: tutorial.settings
      - key: DATABASE_URL
        fromDatabase:
          name: backendag-db
          property: connectionString
    databases:
      - name: backendag-db
        databaseName: backendag
        user: backendag_user